// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dyawdhpxbewafakhgzrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR5YXdkaHB4YmV3YWZha2hnenJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDQwMDMsImV4cCI6MjA2NTQ4MDAwM30.MxzgV5cD-VIavPQM1Z4V_cNvPWt-bHLIti1eWw5UuSE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);